name: Waka Readme
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
